### ISSUE TITLE
Mapping of Entities

### ISSUE THREAD

**Issue by jacauc** [slipx06/Sunsynk-Home-Assistant-Power-Flow-Card#1]
Would it be possible to move the bindings to a separate file? It seems the bindings are duplicated at the bottom of each txt file?

**Comment by slipx06** [comment]
I'm busy working on a new version of the card that will do away with the bindings. You will define the sensors in the card config and will also be able to switch between the different versions (lite, simple full) on the fly as well as hide the daily totals.

![image](https://user-images.githubusercontent.com/7227275/234219474-0e8b7f2d-d888-4357-912e-f0b09b363664.png)

**Comment by jacauc** [comment]
Amazing thanks!
