### ISSUE TITLE
Grid Inverter Load

### ISSUE THREAD

**Issue by jacauc** [slipx06/Sunsynk-Home-Assistant-Power-Flow-Card#2]
I was getting incorrect readings on non-essential and noticed it was using register 167 for calculating the values.
I changed it to 169 and now it displays correctly on my dashboard

<img width="474" alt="image" src="https://user-images.githubusercontent.com/18201320/234252709-5d29ca4f-5048-48de-aecf-32410db2921a.png">

**Comment by slipx06** [comment]
Thanks. I will update the sensor name for the template. I have everything connected to essential so have not been able to check that one.

**Comment by slipx06** [comment]
This is fixed in the new version.
