### ISSUE TITLE
Overall Status String Value

### ISSUE THREAD

**Issue by jacauc** [slipx06/Sunsynk-Home-Assistant-Power-Flow-Card#3]
Love the new layout an configuration of the card.

I'm trying to use string values for overall_state by editing the code as follows, but somehow it just won't take effect. Is there somewhere else I need to change this, or is it home assistant caching the old JS?

If I can get this working, I'll propose an OR statement to check for 
0 OR standby
1 OR selftest
2 OR normal
3 OR alarm
4 OR fault

```
          <circle id="standby" cx="36%" cy="81.75%" r="3.5" fill="${stateObj21.state === 'standby' ? 'blue' : 'transparent'}"/>
          <circle id="selftest" cx="36%" cy="81.75%" r="3.5" fill="${stateObj21.state === 'selftest' ? 'yellow' : 'transparent'}"/>
          <circle id="normal" cx="36%" cy="81.75%" r="3.5" fill="${stateObj21.state === 'normal' ? 'green' : 'transparent'}"/>
          <circle id="alarm" cx="36%" cy="81.75%" r="3.5" fill="${stateObj21.state === 'alarm' ? 'orange' : 'transparent'}"/>
          <circle id="fault" cx="36%" cy="81.75%" r="3.5" fill="${stateObj21.state === 'fault' ? 'red' : 'transparent'}"/>
          <circle id="grid" cx="88.5%" cy="98.5%" r="3.5" fill="${stateObj20.state === 'off' ? 'red' : 'transparent'}"/>
```

Any suggestions to make this work? I've also tried with == instead of === but it didn't seem to make a difference

**Comment by slipx06** [comment]
That should work, assuming your sensor returns those strings. The section of code you posted is for the "full card" card so it will only take affect when using that card style. You will have to change it in three other places if you want to apply to all of the card styles.  

To clear the cache you can append the dashboard resource with "?ver=1" and just increment the version number when you make a change. It will force HA to reload the component. Suggest you also clear cached content from the last hour in your browser

![image](https://user-images.githubusercontent.com/7227275/234935921-7b157b4d-6401-442a-9b63-ef01af5984f8.png)

**Comment by jacauc** [comment]
Works perfectly thanks
