### ISSUE TITLE
Using grid frequency and voltage

### ISSUE THREAD

**Issue by jacauc** [slipx06/Sunsynk-Home-Assistant-Power-Flow-Card#4]
Not sure if it is done on purpose, but I think it makes more sense to use grid frequency and voltage (as opposed to inverter values here:

inverter_grid_voltage_154: sensor.grid_voltage
inverter_load_freq_192: sensor.grid_frequency

![image](https://user-images.githubusercontent.com/18201320/234914493-4b159543-f858-42d0-ae7a-ad9965210d60.png)

**Comment by slipx06** [comment]
The card was built using the following reference and identified modbus registers. I've already updated 167 to 169 which also updates the non-essential formula to (172-169).  As long as you are reading the correct registers for the sensor data. The names may be misleading 

![image](https://user-images.githubusercontent.com/7227275/234937410-07846015-2b88-4aa9-b6e0-fbcfd026226d.png)

**Comment by jacauc** [comment]
Makes sense thanks!
