### ISSUE TITLE
Daily Load Register

### ISSUE THREAD

**Issue by jacauc** [slipx06/Sunsynk-Home-Assistant-Power-Flow-Card#6]
What register # is Daily Load referring to? I do not have this in my esphome code yet
![image](https://user-images.githubusercontent.com/18201320/235238123-724bd905-b8a9-46f8-917d-93f01de5f075.png)

**Comment by slipx06** [comment]
Register 76. I should probably update gridday_76
 
- platform: modbus_controller          #076 Grid Import Day (Buy)
   modbus_controller_id: sunsynk
   name: "Grid Import Day (Buy)"
   id: sunsynk_esphome_grid_import_day
   register_type: holding
   address: 76
   unit_of_measurement: "kWh"
   accuracy_decimals: 1
   device_class: energy
   state_class: total_increasing
   filters: # GOOD
    - lambda: |-
           if (x > 32767) return (x - 65535) / 10;
           else return x /10;

**Comment by jacauc** [comment]
Thanks
